module.exports.data = [
	{
		word: 'Actor',
		spelling: '/ˈæk.tɚ/',
		meaning: 'Diễn viên (nam)',
		audio: {uri: 'https://dictionary.cambridge.org/media/english/us_pron/a/act/actor/actor.mp3'},
		image: {uri: 'https://unsplash.it/600/600'},
		wordType: 'n',
		definition: 'Someone who pretends to be someone else while performing in a film, play, or television or radio programme',
	},
	{
		word: 'Actress',
		spelling: '/ˈæk.trəs/',
		meaning: 'Diễn viên (nữ)',
		audio: {uri: 'https://dictionary.cambridge.org/media/english/us_pron/u/usc/uscld/uscld01818.mp3'},
		image: {uri: 'https://unsplash.it/600/600'},
		wordType: 'n',
		definition: 'A female actor',
	},
	{
		word: 'Thorn',
		spelling: '/ˈæk.trəs/',
		meaning: 'Diễn viên (nữ)',
		audio: {uri: 'https://dictionary.cambridge.org/media/english/us_pron/u/usc/uscld/uscld01818.mp3'},
		image: {uri: 'https://unsplash.it/600/600'},
		wordType: 'n',
		definition: 'A female actor',
	},
	{
		word: 'King',
		spelling: '/ˈæk.trəs/',
		meaning: 'Diễn viên (nữ)',
		audio: {uri: 'https://dictionary.cambridge.org/media/english/us_pron/u/usc/uscld/uscld01818.mp3'},
		image: {uri: 'https://unsplash.it/600/600'},
		wordType: 'n',
		definition: 'A female actor',
	},
	{
		word: 'Vessel',
		spelling: '/ˈæk.trəs/',
		meaning: 'Diễn viên (nữ)',
		audio: {uri: 'https://dictionary.cambridge.org/media/english/us_pron/u/usc/uscld/uscld01818.mp3'},
		image: {uri: 'https://unsplash.it/600/600'},
		wordType: 'n',
		definition: 'A female actor',
	},
	{
		word: 'Time',
		spelling: '/ˈæk.trəs/',
		meaning: 'Diễn viên (nữ)',
		audio: {uri: 'https://dictionary.cambridge.org/media/english/us_pron/u/usc/uscld/uscld01818.mp3'},
		image: {uri: 'https://unsplash.it/600/600'},
		wordType: 'n',
		definition: 'A female actor',
	},
];
